# Generated by Django 4.2.3 on 2024-02-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_paymentgatewaysettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgatewaysettings',
            options={'verbose_name': 'PaymentGatewaySetting', 'verbose_name_plural': 'PaymentGatewaySettings'},
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variation',
            new_name='variations',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.AlterModelTable(
            name='paymentgatewaysettings',
            table='paymentgatewaysettings',
        ),
    ]
